# import required libraries

In [72]:
import numpy as np 
import scipy as sp 
import pandas as pd 
import matplotlib as mpl 
import matplotlib.pyplot as plt 
import seaborn as sns  

from numpy import set_printoptions


from sklearn.tree import DecisionTreeClassifier # model 
from sklearn.ensemble import AdaBoostClassifier # model 
from sklearn.ensemble import RandomForestClassifier # model 
from sklearn.svm import SVC # support vector machine learning model  
from sklearn.linear_model import LogisticRegression # model 
from sklearn.neural_network import MLPClassifier #model 

from sklearn import metrics   # the function computes subset accuracy
from sklearn.model_selection import cross_val_score # evaluate score by cross vali
from sklearn.model_selection import KFold # splitting training set into k part subset with the expection to perform well on new data and unseen  
from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Read data 

In [73]:
spam_data = pd.read_csv('spam_original.csv')

In [74]:
spam_data 

word_freq_make   word_freq_address  ...   capital_run_length_total   spam
0               0.00                0.64  ...                        278      1
1               0.21                0.28  ...                       1028      1
2               0.06                0.00  ...                       2259      1
3               0.00                0.00  ...                        191      1
4               0.00                0.00  ...                        191      1
...              ...                 ...  ...                        ...    ...
4596            0.31                0.00  ...                         88      0
4597            0.00                0.00  ...                         14      0
4598            0.30                0.00  ...                        118      0
4599            0.96                0.00  ...                         78      0
4600            0.00                0.00  ...                         40      0

[4601 rows x 58 columns]

In [75]:
spam_data.shape

(4601, 58)

# Preprocessing : 

###Checking for missing values in each colum using insnull and notnull method to check that whether the value is null or not null. The dataframe will return True for Nan and False  for not Nan.


**The sum method will count the number of missing values of each 

1.   Élément de liste
2.   Élément de liste

individual feature**

In [76]:
spam_data.isnull() .sum()

word_freq_make                 0
 word_freq_address             0
 word_freq_all                 0
 word_freq_3d                  0
 word_freq_our                 0
 word_freq_over                0
 word_freq_remove              0
 word_freq_internet            0
 word_freq_order               0
 word_freq_mail                0
 word_freq_receive             0
 word_freq_will                0
 word_freq_people              0
 word_freq_report              0
 word_freq_addresses           0
 word_freq_free                0
 word_freq_business            0
 word_freq_email               0
 word_freq_you                 0
 word_freq_credit              0
 word_freq_your                0
 word_freq_font                0
 word_freq_000                 0
 word_freq_money               0
 word_freq_hp                  0
 word_freq_hpl                 0
 word_freq_george              0
 word_freq_650                 0
 word_freq_lab                 0
 word_freq_labs                0
 word_freq

The provided test above let us know that there are no missing values in the dataset 

### Check for dtypes 

In [77]:
spam_data.dtypes 

word_freq_make                 float64
 word_freq_address             float64
 word_freq_all                 float64
 word_freq_3d                  float64
 word_freq_our                 float64
 word_freq_over                float64
 word_freq_remove              float64
 word_freq_internet            float64
 word_freq_order               float64
 word_freq_mail                float64
 word_freq_receive             float64
 word_freq_will                float64
 word_freq_people              float64
 word_freq_report              float64
 word_freq_addresses           float64
 word_freq_free                float64
 word_freq_business            float64
 word_freq_email               float64
 word_freq_you                 float64
 word_freq_credit              float64
 word_freq_your                float64
 word_freq_font                float64
 word_freq_000                 float64
 word_freq_money               float64
 word_freq_hp                  float64
 word_freq_hpl           

### Count the number of spam and non-spam(ham) in the spam feature

In [78]:
spam_data[' spam'].value_counts ().sum

<bound method Series.sum of 0    2788
1    1813
Name:  spam, dtype: int64>

From this result we should consider on not spam(0)  > spam 900

### As you might know, machine learning algorithms only work well with numerical data. From the result above, there is no categorical feature on our dataset

### In the following steps, I am going to split dataset into test set and train set and start building machine learning to predict the outcome

In [79]:
X = spam_data.iloc[:,:-1]
y = spam_data.iloc[:,-1]

In [80]:
X.shape

(4601, 57)

In [81]:
y.shape

(4601,)

# Split data into traning and testing set

In [82]:
from sklearn.model_selection  import train_test_split  
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.33,stratify=y,shuffle = True, random_state = 42)
train_test_split(y,shuffle = True)
print(X_train.shape)

(3082, 57)


In [83]:
print(X_train)

      word_freq_make  ...   capital_run_length_total
316             0.00  ...                         87
2703            0.00  ...                         37
947             0.00  ...                         71
3015            0.00  ...                         64
3041            0.00  ...                        227
...              ...  ...                        ...
623             0.19  ...                        870
1861            0.00  ...                         14
2366            0.00  ...                         13
229             0.00  ...                        156
3114            0.00  ...                         65

[3082 rows x 57 columns]


In [84]:
print(X_test)

      word_freq_make  ...   capital_run_length_total
1534            0.15  ...                        801
3474            0.00  ...                         11
3107            0.00  ...                          9
3118            0.00  ...                         49
1911            0.00  ...                        185
...              ...  ...                        ...
3661            0.00  ...                          5
3736            0.00  ...                         43
2354            0.00  ...                         53
1609            0.00  ...                        208
2014            0.00  ...                       1506

[1519 rows x 57 columns]


In [85]:
print(y_train)

316     1
2703    0
947     1
3015    0
3041    0
       ..
623     1
1861    0
2366    0
229     1
3114    0
Name:  spam, Length: 3082, dtype: int64


In [86]:
print(y_test)

1534    1
3474    0
3107    0
3118    0
1911    0
       ..
3661    0
3736    0
2354    0
1609    1
2014    0
Name:  spam, Length: 1519, dtype: int64


In [87]:
print(y_test.shape)

(1519,)


# Feature selection : Removing features with low variance 

In [88]:
from sklearn.feature_selection import VarianceThreshold, RFE, SelectFromModel, SelectKBest, f_classif, chi2, mutual_info_classif

##1 : Removing features with low variance 

In [89]:
set_variance_threshold = VarianceThreshold()
# New X_train 
X_train_remove_variance = set_variance_threshold .fit_transform(X_train)
X_train_remove_variance.shape

# I will not remove any features from this method

(3082, 57)

## Removing unvariate feature

In [90]:
set_chi2 = SelectKBest(chi2, k = 4 ) # select 4 features 
# X_train new 
X_train_chi2 = set_chi2.fit_transform(X_train,y_train)
print(set_chi2.get_support())
print(set_chi2.get_params())
# summarize score 
# the last three elements in the array are true, which means the last three features was selected by this method
print(X_train_chi2.shape)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True  True  True]
{'k': 4, 'score_func': <function chi2 at 0x7f5d67199158>}
(3082, 4)


In [91]:
# 2 use f test 

set_f = SelectKBest(f_classif,k = 4)
# New x_train
X_train_f = set_f.fit_transform(X_train,y_train)
print(set_f.get_support())
print(set_f.get_params())
print(X_train_f.shape)

[False False False False False False  True False False False False False
 False False False False False False False False  True False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True False False False False]
{'k': 4, 'score_func': <function f_classif at 0x7f5d67199048>}
(3082, 4)


In [92]:
sel_mutual = SelectKBest(mutual_info_classif, k=4)
# New train data 
X_train_mutual = sel_mutual.fit_transform(X_train, y_train)
print(sel_mutual.get_support())
print(sel_mutual.get_params())
print(X_train_mutual.shape)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False  True  True False  True  True False]
{'k': 4, 'score_func': <function mutual_info_classif at 0x7f5d6712b400>}
(3082, 4)


## Recursive Feature Elimination

##Feature extraction

In [93]:
model = LogisticRegression(solver='lbfgs',class_weight='balanced',max_iter=10000)
rfe = RFE(model,3)
fit = rfe.fit(X_train,y_train)
print("Number of features : %d" % (fit.n_features_))
print("selected features :%s"% (fit.support_))
print("Feature Ranking : %s" % (fit.ranking_))
# as you can see that RFF choose the top 3 features
# word_freg_remove, char_freg_dollor, word_freg_hpl

Number of features : 3
selected features :[False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True False False False False]
Feature Ranking : [37 44 36 18 21 17  1 25 14 32 52 45 51 54  7 15 13 42 50  9 46 47  2 29
 10  3  1 35  4 48 38 49 23 34 19 30 41 26 27 39  8  6 16 12 24  5 28 20
 22 43 33 31  1 11 40 53 55]


## Principal component analysis

In [94]:
# Feature extraction 

pca = PCA(n_components=3)

fit = pca.fit(X_train)

print("Explained Variance :%s" % (fit.explained_variance_ratio_))
print(fit.components_)

Explained Variance :[0.90377592 0.0935616  0.00257124]
[[ 4.76126393e-05 -4.83896793e-05  7.58548761e-05  7.19250324e-05
   1.94538944e-05  4.38895537e-05 -1.20627595e-06  3.19392530e-05
   1.22302227e-04  1.06226358e-04  3.98977946e-05  4.14469416e-05
   5.01736115e-05  9.17663658e-05  7.56163895e-05  1.64299246e-05
   5.07152679e-05  4.74933021e-05 -1.64743768e-07  7.80708401e-05
   1.48383919e-04  1.26037316e-04  9.53755311e-05  5.86552494e-05
  -1.19984751e-04 -1.06805475e-04 -5.52985815e-04 -7.07460945e-05
  -6.21070203e-05 -4.98255978e-05 -3.40461487e-05 -2.81381431e-05
   6.08688112e-06 -2.71835135e-05 -4.68194342e-05 -3.64350091e-05
   2.31999587e-06 -3.28237371e-06 -3.22078107e-05 -1.96908152e-05
  -1.31344272e-05 -7.62134515e-05 -1.11895152e-05 -4.41759840e-05
  -1.70839090e-04 -6.69061186e-05  1.82569665e-06 -9.27807568e-06
   2.28404061e-05  9.74379518e-05 -7.36579342e-07  6.06089780e-05
   9.33408485e-05  4.13900023e-05  1.33149219e-02  2.08777999e-01
   9.77872137e-01]
 [

## Feature importances 

In [95]:
Extra = ExtraTreesClassifier()
Extra.fit(X_train,y_train)
print(Extra.feature_importances_)
# As you can see from the array, I will list some important features 
# word_freg_remove, word_freg_free, word_freg_your

[0.00949237 0.00979181 0.01601001 0.00205534 0.03493615 0.01338952
 0.05380177 0.01885998 0.0144166  0.01426198 0.01915101 0.01429207
 0.00653081 0.00402525 0.01432469 0.04198207 0.02258639 0.01536572
 0.03370186 0.00990367 0.06995643 0.00643588 0.05145515 0.03409931
 0.03883338 0.01924155 0.03033589 0.00907727 0.00574326 0.00720984
 0.00382816 0.00232604 0.00561705 0.00268913 0.00523968 0.00708483
 0.01590179 0.00136721 0.00631548 0.00318152 0.00237163 0.01143261
 0.00478447 0.0068303  0.01563597 0.01927668 0.00077192 0.00241193
 0.00744845 0.01390021 0.0043153  0.04814493 0.05501854 0.0052077
 0.03205417 0.04037527 0.03520198]


#Modeling and Compare machine learning algorithms 

## Choose the best althogrithm for training and testing 

# 1  LogisticRegression 

## Raw data model 

In [132]:
model = LogisticRegression(solver='lbfgs',class_weight='balanced',max_iter=10000)
model.fit(X_train,y_train)
# train the data into n- k part data
kfold = KFold(n_splits= 3,random_state = 42)
result = cross_val_score(model,X_train,y_train,cv= kfold)
print("Accuracy ",result.mean()*100.0, result.std()*100.0)
predict = model.predict(X_test)
#print(confusion_matrix(y_test,predict))
#print(classification_report(y_test,predict))
print(predict)
print("Metrics Accuracy",metrics.accuracy_score(y_test,predict)*100.0)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


Accuracy  92.63434606733627 0.7241125494507812
[1 0 0 ... 0 1 1]
Metrics Accuracy 92.89005924950625


## Model with chiquare2 

In [134]:
model_1 = LogisticRegression(solver='lbfgs',class_weight='balanced',max_iter=10000)
model_1.fit(X_train_chi2,y_train)
kfold = KFold(n_splits = 3,random_state = 42)
X_test_chi2 = set_chi2.transform(X_test)
result_1 = cross_val_score(model_1,X_train_chi2,y_train,cv = kfold)
predict_1 = model_1.predict(X_test_chi2)
print("Accuracy",result_1.mean()*100.0,result.std()*100.0)
print(confusion_matrix(y_test,predict_1))
print(classification_report(y_test,predict_1))
# Model with chiquare2 is not fit in this case 
print(predict_1)
print("Accuracy metrics",metrics.accuracy_score(y_test,predict_1)*100.0)

Accuracy 77.51374370593206 0.7241125494507812
[[749 171]
 [199 400]]
              precision    recall  f1-score   support

           0       0.79      0.81      0.80       920
           1       0.70      0.67      0.68       599

    accuracy                           0.76      1519
   macro avg       0.75      0.74      0.74      1519
weighted avg       0.75      0.76      0.76      1519

[1 0 0 ... 0 1 1]
Accuracy metrics 75.64186965108625


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


## Model with remove variance

In [118]:
model_3 = LogisticRegression(solver='lbfgs',class_weight='balanced',max_iter=10000)
model_3.fit(X_train_remove_variance,y_train)
# transform x test
X_test_remove_variance = set_variance_threshold.transform(X_test)
kfold = KFold(n_splits = 3,random_state = 42)
result_2 = cross_val_score(model_3,X_train_remove_variance,y_train,cv = kfold)
predict_2 = model_3.predict(X_train_remove_variance)
#print(X_test.shape)
#print(X_test_remove_variance.shape)
print("Accuracy",result_2.mean()*100.0,result_2.std()*100.0)
print("Predict Result",predict_2)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


Accuracy 92.63434606733627 0.7241125494507812
Predict Result [1 0 1 ... 0 1 0]


## Model with train_f

In [122]:
model_4 = LogisticRegression(solver='lbfgs',class_weight='balanced',max_iter=10000)

model_4.fit(X_train_f,y_train)

X_test_f = set_f.transform(X_test)
print(X_test_f.shape)

kfold = KFold(n_splits = 3,random_state = 42)
result_3 = cross_val_score(model_4,X_train_f,y_train, cv = kfold)
predict_4 = model_4.predict(X_test_f)
print(confusion_matrix(y_test,predict_4))
print(classification_report(y_test,predict_4))
print(predict_4)
print(result_3.mean()*100.0)

(1519, 4)
[[841  79]
 [183 416]]
              precision    recall  f1-score   support

           0       0.82      0.91      0.87       920
           1       0.84      0.69      0.76       599

    accuracy                           0.83      1519
   macro avg       0.83      0.80      0.81      1519
weighted avg       0.83      0.83      0.82      1519

[1 0 0 ... 0 1 0]
85.13864314608047


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


# Conclusion : After training and testing model on raw data and model by feature selection. I come to conclusion that the accuracy would 93% With logisticClassificaer algorithm

#2 :  RandomForest

##1. Raw data 

In [130]:
random = RandomForestClassifier()
random.fit(X_train,y_train) 
kfold = KFold(n_splits = 3,random_state = 42)
result_4 = cross_val_score(random,X_train,y_train,cv = kfold)
predict_5 = random.predict(X_test)
print(predict_5)
print(confusion_matrix(y_test,predict_5))
print(classification_report(y_test,predict_5 ))
print("Accuracy",result_4.mean()*100.0)
print("Metrics Accuracy",metrics.accuracy_score(y_test,predict_5)*100.0)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


[1 0 0 ... 0 1 0]
[[894  26]
 [ 48 551]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       920
           1       0.95      0.92      0.94       599

    accuracy                           0.95      1519
   macro avg       0.95      0.95      0.95      1519
weighted avg       0.95      0.95      0.95      1519

Accuracy 94.7432613848907
Metrics Accuracy 95.12837393021725


## 1 : Chiquare

In [153]:
random_1 = RandomForestClassifier(max_depth= 2 , random_state=0)

random_1.fit(X_train_chi2,y_train)

kfold = KFold(n_splits = 3,random_state = 42)

result_5 = cross_val_score(random_1,X_train_chi2,y_train,cv = kfold)

X_test_chi2_1 = set_chi2.transform(X_test)
print(X_test_chi2_1.shape)

predict_5 = random_1.predict(X_test_chi2_1)

print(confusion_matrix(y_test,predict_5))
print(classification_report(y_test,predict_5)) 

print("Metrics accuracy",metrics.accuracy_score(y_test,predict_5) )
print(result_5.mean()*100.0)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


(1519, 4)
[[765 155]
 [195 404]]
              precision    recall  f1-score   support

           0       0.80      0.83      0.81       920
           1       0.72      0.67      0.70       599

    accuracy                           0.77      1519
   macro avg       0.76      0.75      0.76      1519
weighted avg       0.77      0.77      0.77      1519

Metrics accuracy 0.7695852534562212
78.81180247456166


## 3 : Remove variance 


In [163]:
random_2 = RandomForestClassifier(max_depth = 2 , random_state= 0)

random_2.fit(X_train_remove_variance,y_train)

kfold = KFold(n_splits = 3,random_state = 42)
result_6 = cross_val_score(random_2,X_train_remove_variance,y_train,cv = kfold)
X_test_remove_variance = set_variance_threshold.transform(X_test)
predict_6 = random_2.predict(X_test_remove_variance)
print(confusion_matrix(y_test,predict_6))
print(classification_report(y_test,predict_6))
print(predict_6)
print(result_6.mean()*100.0)
print("Metrics Accuracy",metrics.accuracy_score(y_test,predict_6)*100.0)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


[[900  20]
 [154 445]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91       920
           1       0.96      0.74      0.84       599

    accuracy                           0.89      1519
   macro avg       0.91      0.86      0.87      1519
weighted avg       0.89      0.89      0.88      1519

[1 0 0 ... 0 1 0]
88.48095582691457
Metrics Accuracy 88.54509545753785


## 4 : Random_f 

In [108]:
random_3 = RandomForestClassifier(max_depth = 2 , random_state =0)
random_3.fit(X_train_f, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [109]:
X_test_f = set_f.transform(X_test)

predict_6 = random_3.predict(X_test_f)

print(predict_6)
print(confusion_matrix(y_test,predict_6) )
print(classification_report(y_test,predict_6))

[1 0 0 ... 0 1 0]
[[860  60]
 [173 426]]
              precision    recall  f1-score   support

           0       0.83      0.93      0.88       920
           1       0.88      0.71      0.79       599

    accuracy                           0.85      1519
   macro avg       0.85      0.82      0.83      1519
weighted avg       0.85      0.85      0.84      1519



# 3 : Decision_Tree

## 1 . Raw Data 

In [110]:
Decision = DecisionTreeClassifier()
Decision.fit(X_train,y_train)
predict = Decision.predict(X_test)
print(confusion_matrix(y_test,predict))
print(classification_report(y_test,predict))
print(predict)

[[836  84]
 [ 69 530]]
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       920
           1       0.86      0.88      0.87       599

    accuracy                           0.90      1519
   macro avg       0.89      0.90      0.90      1519
weighted avg       0.90      0.90      0.90      1519

[1 0 0 ... 0 1 0]


## 2 : Chiquare

In [111]:
Decision_1 = DecisionTreeClassifier( )

Decision_1.fit(X_train_chi2,y_train) 
# New train data
X_test_chi2 = set_chi2.transform(X_test)

predict_7 = Decision_1.predict(X_test_chi2) 

print(predict_7)
print(confusion_matrix(y_test,predict_7))
print(classification_report(y_test,predict_7))

[1 0 0 ... 0 0 0]
[[785 135]
 [146 453]]
              precision    recall  f1-score   support

           0       0.84      0.85      0.85       920
           1       0.77      0.76      0.76       599

    accuracy                           0.82      1519
   macro avg       0.81      0.80      0.81      1519
weighted avg       0.81      0.82      0.81      1519



## 3 : Remove with variance 

In [112]:
Decision_2 = DecisionTreeClassifier(max_depth = 2, random_state = 0) 
Decision_2.fit(X_train_remove_variance,y_train)

X_test_remove_variance = set_variance_threshold.transform(X_test)

predict_8 = Decision_2.predict(X_test_remove_variance)  

print(confusion_matrix(y_test,predict_8)) 
print(classification_report(y_test,predict_8))

[[885  35]
 [175 424]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89       920
           1       0.92      0.71      0.80       599

    accuracy                           0.86      1519
   macro avg       0.88      0.83      0.85      1519
weighted avg       0.87      0.86      0.86      1519



## 4 Model with random_f 

In [113]:
Decision_3 = DecisionTreeClassifier(max_depth = 2, random_state = 0)

Decision_3.fit(X_train_f,y_train)

X_test_f = set_f.transform(X_test)

predict_9 = Decision_3.predict(X_test_f)

print(confusion_matrix(y_test,predict_9))
print(classification_report(y_test,predict_9))
print(predict_9)

[[858  62]
 [174 425]]
              precision    recall  f1-score   support

           0       0.83      0.93      0.88       920
           1       0.87      0.71      0.78       599

    accuracy                           0.84      1519
   macro avg       0.85      0.82      0.83      1519
weighted avg       0.85      0.84      0.84      1519

[1 0 0 ... 0 1 0]
